# Generated by Django 5.1.2 on 2024-11-08 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='is_availabe',
            new_name='is_available',
        ),
    ]
