# Generated by Django 5.1.2 on 2024-12-10 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_data',
            new_name='total_tax',
        ),
    ]
